# Generated by Django 2.1.4 on 2018-12-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SignIn',
            new_name='Student',
        ),
    ]
