# Generated by Django 2.1.4 on 2018-12-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signins', '0002_auto_20181210_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
